### ISSUE TITLE
Related tags not showing tag title

### ISSUE THREAD

**Issue by allanwhite** [daticahealth/Datica-V3#1]
I want to display the `title` field in a tag taxonomy (`taxonomies/tags/`) entry in a partial: https://github.com/daticahealth/Datica-V3/blob/master/public/site/themes/main/partials/tag-list-plain.html

The tag loop in the `tag-list-plain` partial is pulling the related entries' title field, instead of the tag title.

The containing partial is https://github.com/daticahealth/Datica-V3/blob/master/public/site/themes/main/partials/academy-card-h.html

In a collection view, it just shows the slug because I relied on `{{value}}` to render the output:
![image](https://user-images.githubusercontent.com/887931/73566919-fdbb4080-4419-11ea-80bd-6038dabe6bed.png)

Desired output example, from an entry: 
![image](https://user-images.githubusercontent.com/887931/73566843-c187e000-4419-11ea-822a-799dc49660ba.png)

**Comment by edalzell** [comment]
@allanwhite what url do you see that on?
