### ISSUE TITLE
Redesign nav approach

### ISSUE THREAD

**Issue by allanwhite** [daticahealth/Datica-V3#12]
The Big Kahuna nav plugin is too limited. 

- Create a fieldset for navigation, with pages added to top-level categories. 
- Rebuild nav components for 1.) footer and 2.) primary nav. 

Update 5/14/20: Everything looks good other than product highlight padding. See attached screenshot.

![Screen Shot 2020-05-14 at 3 56 34 PM](https://user-images.githubusercontent.com/56596364/81985358-c43ec780-95fb-11ea-85c4-19be3a6e1b21.png)

**Update 5/15/20:** Padding appears to have been fixed. Statamic CP for nav and front end are out of sync for products, i.e. Compliance dropdown is still showing Monitor and Compliant Kubernetes Service when it should only show Cloud Compliance on the front end but the CP nav lists Cloud Compliance as the only item in the dropdown.

**Comment by allanwhite** [comment]
Old CSS: https://github.com/daticahealth/seldon-middleman/blob/master/source/assets/scss/modules/nav.scss

**Comment by 1stevengrant** [comment]
@oeclovreher have a play around with `/cp/globals/header_nav` for the header and `/cp/globals/footer_nav` for the footer nav
