### ISSUE TITLE
Global Form Styling Issue

### ISSUE THREAD

**Issue by oeclovreher** [daticahealth/Datica-V3#13]
The form styling appears to be a problem globally. See screenshots below:

**Incorrect styling screengrab:** ![Screen Shot 2020-05-15 at 11 10 05 AM](https://user-images.githubusercontent.com/56596364/82072790-db35f600-969d-11ea-850e-86e5dac2dcdf.png)

**Correct styling screengrab from seldon/middleman site:** 
![Screen Shot 2020-05-15 at 11 20 59 AM](https://user-images.githubusercontent.com/56596364/82073012-32d46180-969e-11ea-907b-17badded4de4.png)

**Comment by 1stevengrant** [comment]
@oeclovreher now on staging https://datica.ghijkdev.co.uk/guide/gdpr-compliance/
