### ISSUE TITLE
Forms List Not Populating in Statmic CP

### ISSUE THREAD

**Issue by oeclovreher** [daticahealth/Datica-V3#14]
Forms are populating on their respective pages in the CP but not here: [https://datica.ghijkdev.co.uk/cp/forms](https://datica.ghijkdev.co.uk/cp/forms). Not sure if we need to manually recreate/what the process looks like for populating those.

**Comment by 1stevengrant** [comment]
I don't see any forms other than `contact me` as having been configured yet.

Can you add a list of all the forms and I can do the needful with those?
