### ISSUE TITLE
Events Header Unstyled 

### ISSUE THREAD

**Issue by oeclovreher** [daticahealth/Datica-V3#15]
Header items on the Events page are coming in unstyled.

![Screen Shot 2020-05-15 at 11 45 16 AM](https://user-images.githubusercontent.com/56596364/82075353-b9d70900-96a1-11ea-93a7-da3363a7f3a0.png)

**Comment by 1stevengrant** [comment]
styled the header and put this onto staging but noticing that the events below could do with some ❤️ too @oeclovreher
