### ISSUE TITLE
Create Modular Homepage

### ISSUE THREAD

**Issue by oeclovreher** [daticahealth/Datica-V3#17]
Taking the current homepage and making it modular like /compliance/ and /ehr-integration/. Allan mentioned that we can leverage content models and components to build this page. There will be some unique areas, but we can add the content block "library".

Not necessary for MVP, but if not possible before MVP launch, will need to send Steven content updates prior to go-live.

**Comment by 1stevengrant** [comment]
made the general content blocks available now on staging @oeclovreher
