### ISSUE TITLE
Add CTAs to Collections

### ISSUE THREAD

**Issue by oeclovreher** [daticahealth/Datica-V3#19]
We need to update templates for: Academy, Blog, Press, Customer Spotlights, Webinars to include Calls To Action (https://datica.ghijkdev.co.uk/cp/collections/entries/cta) at the bottom of each entry. See bottom of this page for example (https://datica.com/press-release/datica-fast-tracks-vigilanz-covid-quick-start-implementations-free-six-mos/).

**Comment by 1stevengrant** [comment]
pushed a bunch of ctas into those now
