### ISSUE TITLE
Add buttons to Feature Blocks set (Content Block)

### ISSUE THREAD

**Issue by oeclovreher** [daticahealth/Datica-V3#25]
Would like to be able to add buttons to "Feature Blocks" like what is enabled in "Text + Image"

![Screen Shot 2020-05-22 at 1 59 21 PM](https://user-images.githubusercontent.com/56596364/82700761-75fd7a00-9c34-11ea-888a-fdece9464973.png)

**Comment by 1stevengrant** [comment]
now on staging
