### ISSUE TITLE
Leadership list view

### ISSUE THREAD

**Issue by allanwhite** [daticahealth/Datica-V3#8]
[Example view here](https://datica.com/leadership). 

Oscar's Review 5/5: List view only pulling in "Person Category" containing "Datica Executive". The drop down for "Person Category" doesn't match up with what is currently there (see attached screenshot).

![Screen Shot 2020-05-05 at 10 37 41 AM](https://user-images.githubusercontent.com/56596364/81085159-75d34f80-8ebc-11ea-9752-f111d3b6ad17.png)

Update: 5/6: Everything is pulling in correctly now.

**Comment by 1stevengrant** [comment]
@oeclovreher I've changed it so that the labels match what's defined in the field
